# No API keys required for basic functionality
# .streamlit/secrets.toml
CRYPTOCOMPARE_API_KEY = "e02ae767a80f4f72d10f4b822b83f4e71bf2217d51f3cccf3d1734759b6db3b0"

# Add your email secrets here too if you haven't already
EMAIL_ADDRESS = "your_email@example.com"
EMAIL_PASSWORD = "your_app_password"
SMTP_SERVER = "smtp.example.com"
SMTP_PORT = 587